### ISSUE TITLE
Migration: Installation stuck on step 2

### ISSUE THREAD

**Issue by Grishkaone** [marienfressinaud/FreshRSS#4044]
Hello there 😊

I'm trying to install FreshRSS on my Synology. So far :

- All files are in a folder /volume 1/web/rss/
- MariaDB is installed and running.
- Database "rss" is created, along the user "frss"
- The web server run on PHP 7.4 with Apache 2.4
- I Can access the page https://mydomain/rss/ and it start https://domain/rss/p/i/.
- I choose the language, then everything is green on step 1.
- On step 2, I add all informations about the database and press "OK" : the page load, come back to step 2 without any error. I can't get pass the step 2.

`session.save_path` is writeable and I can see the file there. The database is OK and runs fine with a mediawiki installation.

I don't where I can see what's wrong.

Can you help me ? Unfortunately my NAS is DS218 wich is not compatible with the Docker package.

Thanks 🖖

**Comment by math-GH** [comment]
Could you support us a screenshot?

**Comment by Grishkaone** [comment]
Hey @math-GH  !

Here they come : with 3 different url tests (local, local+port and socket provided by the MariaDB package :

![Capture d’écran 2021-12-08 à 19 59 59](https://user-images.githubusercontent.com/46840243/145267914-17291bfb-9a23-402e-aea5-28926d0d67b3.png)
![Capture d’écran 2021-12-08 à 20 00 14](https://user-images.githubusercontent.com/46840243/145267922-1134c0c7-db2b-48ea-b31a-c5d4512b4c69.png)
![Capture d’écran 2021-12-08 à 20 00 30](https://user-images.githubusercontent.com/46840243/145267923-a8b83516-378e-4a76-9771-319e7bd41fb0.png)

The user on the phpMyAdmin/database side :
![Capture d’écran 2021-12-08 à 20 02 45](https://user-images.githubusercontent.com/46840243/145268167-c88c52a8-7d99-4721-b438-05a7608978cc.png)

And a short video : each time I click on the button, the page reload to the exact same state, without error.
https://user-images.githubusercontent.com/46840243/145268493-5189fc3f-84b9-4612-92ac-20db42b91e3e.mov

I hope this help

**Comment by math-GH** [comment]
maybe the Prefix makes an problem?

could you check the console and network tab in your browser?

**Comment by Grishkaone** [comment]
Well, nothing in Safari's console.
I tried too in Firefox, and there is juste one error concerning the favicon (GET https://domain/favicon.ico), wich is normal since there is no favicon at this place.

**Comment by Grishkaone** [comment]
Also, I tried without prefix, same issue.

**Comment by math-GH** [comment]
Strange, that there is no error message.

Maybe a PHP extension is missed? Could you paste your PHPinfo()?
(unfortunately I am not the expert which extension is mandatory)

**Comment by Alkarex** [comment]
Hello @Grishkaone 
Could you please post your Apache logs?

**Comment by Grishkaone** [comment]
Hi !

Here we go with the full phpinfo() in PDF :
[PHP 7.4.18 - phpinfo().pdf](https://github.com/FreshRSS/FreshRSS/files/7683306/PHP.7.4.18.-.phpinfo.pdf)

About the apache log, I've tried with apache 2.4, so there is the file :
[log.txt](https://github.com/FreshRSS/FreshRSS/files/7683456/log.txt)

Then I saw something interesting : if I put a wrong DB password or user on purpose, there is an error 
`Arf ! Vérifiez les informations d’accès à la base de données. : Access to database is denied for `frss`: SQLSTATE[HY000] [1045] Access denied for user 'frss'@'localhost' (using password: YES)`

So the problem could be on the DB side ? Maybe the user's privileges ?
Nothing there two.

So this morning I tried the holy grenade : I wiped the FreshRSS folder, downloaded it again, put the files, deal with the folders right for the HTTP group and... it worked. The DB info were accepted, and I created an user. And now... blank page.
The Apache log show this :

```
2021-12-09T09:28:21+01:00 Krypton [Thu Dec 09 09:28:21 2021] [error] [client 192.168.0.41] FastCGI: server "/default-php-9f1e642a-0d20-4664-8934-c51d34f609de" stderr: PHP message: PHP Warning:  date(): Invalid date.timezone value 'Lastest SynoErr', we selected the timezone 'UTC' for now. in /volume1/web/rss/lib/Minz/Log.php on line 62PHP message: PHP Fatal error:  Uncaught BadFunctionCallException: @eaDir migration cannot be called. in /volume1/web/rss/lib/Minz/Migrator.php:172, referer: http://192.168.0.43/rss/p/i/?step=4
2021-12-09T09:28:21+01:00 Krypton [Thu Dec 09 09:28:21 2021] [error] [client 192.168.0.41] FastCGI: server "/default-php-9f1e642a-0d20-4664-8934-c51d34f609de" stderr: Stack trace:, referer: http://192.168.0.43/rss/p/i/?step=4
2021-12-09T09:28:21+01:00 Krypton [Thu Dec 09 09:28:21 2021] [error] [client 192.168.0.41] FastCGI: server "/default-php-9f1e642a-0d20-4664-8934-c51d34f609de" stderr: #0 /volume1/web/rss/lib/Minz/Migrator.php(154): Minz_Migrator->addMigration('@eaDir', 'FreshRSS_Migrat...'), referer: http://192.168.0.43/rss/p/i/?step=4
2021-12-09T09:28:21+01:00 Krypton [Thu Dec 09 09:28:21 2021] [error] [client 192.168.0.41] FastCGI: server "/default-php-9f1e642a-0d20-4664-8934-c51d34f609de" stderr: #1 /volume1/web/rss/lib/lib_install.php(120): Minz_Migrator->__construct('/volume1/web/rs...'), referer: http://192.168.0.43/rss/p/i/?step=4
2021-12-09T09:28:21+01:00 Krypton [Thu Dec 09 09:28:21 2021] [error] [client 192.168.0.41] FastCGI: server "/default-php-9f1e642a-0d20-4664-8934-c51d34f609de" stderr: #2 /volume1/web/rss/app/install.php(642): setupMigrations(), referer: http://192.168.0.43/rss/p/i/?step=4
2021-12-09T09:28:21+01:00 Krypton [Thu Dec 09 09:28:21 2021] [error] [client 192.168.0.41] FastCGI: server "/default-php-9f1e642a-0d20-4664-8934-c51d34f609de" stderr: #3 /volume1/web/rss/p/i/index.php(30): require('/volume1/web/rs...'), referer: http://192.168.0.43/rss/p/i/?step=4
2021-12-09T09:28:21+01:00 Krypton [Thu Dec 09 09:28:21 2021] [error] [client 192.168.0.41] FastCGI: server "/default-php-9f1e642a-0d20-4664-8934-c51d34f609de" stderr: #4 {main}, referer: http://192.168.0.43/rss/p/i/?step=4
2021-12-09T09:28:21+01:00 Krypton [Thu Dec 09 09:28:21 2021] [error] [client 192.168.0.41] FastCGI: server "/default-php-9f1e642a-0d20-4664-8934-c51d34f609de" stderr:   thrown in /volume1/web/rss/lib/Minz/Migrator.php on line 172 'Lastest SynoErr', we selected the timezone 'UTC' for now. in /volume1/web/rss/lib/Minz/Log.php on line 62PHP message: PHP Fatal error:  Uncaught BadFunctionCallException: @eaDir migration cannot be called. in /volume1/web/rss/lib/Minz/Migrator.php:172, referer: http://192.168.0.43/rss/p/i/?step=4
```

(this part is also at the end of the log.txt file).

**Comment by math-GH** [comment]
Could you fix the time zone issue?

**Comment by Grishkaone** [comment]
Hey !

I wish I could...
In the Synology GUI, all is right for date, time and timezone.
In SSH the `date` command give is OK too.
In the phpinfo, the **date.timezone** is wrong : Latest SynoError.

So I stopped all web services (PHP, Apache, WebStation, MariaDB, etc.) before starting them again.
`date.timezone : Europe/Brussels` 👍 

Next, https://IP/rss/p : I choose to keep the current installation, ("garder l'ancienne installation"). On step 5 I click on "Terminer l'installation" and... blank page. The apache log show this :

```
2021-12-12T11:19:54+01:00 Krypton [Sun Dec 12 11:19:54.285937 2021] [proxy_fcgi:error] [pid 26947:tid 547331498400] [client 192.168.0.41:54704] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught BadFunctionCallException: @eaDir migration cannot be called. in /volume1/web/rss/lib/Minz/Migrator.php:172\n
Stack trace:\n#0 /volume1/web/rss/lib/Minz/Migrator.php(154): Minz_Migrator->addMigration('@eaDir', 'FreshRSS_Migrat...')\n
#1 /volume1/web/rss/lib/lib_install.php(120): Minz_Migrator->__construct('/volume1/web/rs...')\n
#2 /volume1/web/rss/app/install.php(642): setupMigrations()\n
#3 /volume1/web/rss/p/i/index.php(30): require('/volume1/web/rs...')\n
#4 {main}\n  thrown in /volume1/web/rss/lib/Minz/Migrator.php on line 172', referer: http://192.168.0.43/rss/p/i/index.php?step=4
```

As a precaution, I tried from the local IP and from the domain, same result.
So, here we go again :
1. Delete /rss folder
2. Delete rss database
3. download FreshRSS
4. Move file to /rss folder
5. Create rrs database
6. create frss user
7. check phpinfo for `date.timezone`
8. open /rss/p in browser

At this point, I must admit that I was out of hope.
But...
**It work !** 🎉 I can finally use this beautiful rss reader 🤩.

I still don't understand _why_ it didn't work, and I hope the log can help you understand it. In any case, thank you for your help !

**Comment by Alkarex** [comment]
Maybe @marienfressinaud would have an idea; potentially a bug in the Minz Migration logic.

**Comment by marienfressinaud** [comment]
It's not really a bug in the logic of the Migrator, more likely an unexpected behavior of your NAS. It seems it creates an invisible file named `@eaDir` under the `app/migrations/` folder (see [this thread](https://community.synology.com/enu/forum/17/post/4024)). The Migrator considers the files in this folder to be valid PHP files but can't find any callable method in the `@eaDir` file and fails legitimately.

On our side, we could ignore the filenames [that don't end with `.php`](https://github.com/FreshRSS/FreshRSS/blob/edge/lib/Minz/Migrator.php#L138).

**Comment by Grishkaone** [comment]
Hey !

I came across [this article](http://www.ghanassia.com/?id=supprimer-les-repertoires-eaDir-sur-synology): `@eaDir` folders seem to be related to content indexing or rights management.

![eadir](https://user-images.githubusercontent.com/46840243/145780823-04e50b96-c818-4121-97ed-922a1300c9c9.jpg)

I don't know what rules the creation of these folders follows: on My NAS the web folder is not indexed. And as you can see on the picture, all the subfolders are not affected.
