### ISSUE TITLE
[BUG]error exporting favs - php-gmp extension needed for 32bit

### ISSUE THREAD

**Issue by rezad1393** [marienfressinaud/FreshRSS#5233]
**Describe the bug**
when I try to export  with "Export your favourites " enabled I get an empty error page.
`{ "id": "user/testuser/state/org.freshrss/starred", "title": "List of favourite articles", "author": "testuser", "items": [ `

in nginx log I see:
```
023/03/27 13:44:16 [error] 916#916: *53731 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function gmp_strval() in /mnt/mydata/apps/app-data/nginx/webapps/freshrss/app/Models/Entry.php:766
Stack trace:
#0 /mnt/mydata/apps/app-data/nginx/webapps/freshrss/app/Models/Entry.php(789): FreshRSS_Entry::dec2hex()
#1 /mnt/mydata/apps/app-data/nginx/webapps/freshrss/app/views/helpers/export/articles.phtml(33): FreshRSS_Entry->toGReader()
#2 /mnt/mydata/apps/app-data/nginx/webapps/freshrss/lib/Minz/View.php(88): include('...')
#3 /mnt/mydata/apps/app-data/nginx/webapps/freshrss/lib/Minz/View.php(138): Minz_View->includeFile()
#4 /mnt/mydata/apps/app-data/nginx/webapps/freshrss/lib/Minz/View.php(149): Minz_View->renderHelper()
#5 /mnt/mydata/apps/app-data/nginx/webapps/freshrss/app/Services/ExportService.php(89): Minz_View->helperToString()
#6 /mnt/mydata/apps/app-data/nginx/webapps/freshrss/app/Controllers/importExportController.php(600): FreshRSS_Export_Service->generateStarredEntries()
#7 /mnt/mydata/apps/app-data/nginx/webapps/fr" while reading response header from upstream, client: 192.168.1.101, server: odroid, request: "POST /i/?c=importExport&a=export HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "mydomain:1083"
```

**Environment information (please complete the following information):**
- Device: odroid
- OS: ubuntu arm 
- Browser:firefox 
- FreshRSS version:  1.21.0 
apt list --installed |grep sql                                   

libsqlite3-0/jammy-updates,jammy-security,now 3.37.2-2ubuntu0.1 armhf [installed,automatic]
php-sqlite3/jammy,now 2:8.1+92ubuntu1 all [installed]
php8.1-sqlite3/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.11 armhf [installed,automatic]

**Comment by Alkarex** [comment]
Hello,
The extension `php-gmp` seems to be missing, and is needed in the case of 32-bit platforms.

Cf. our documentation https://freshrss.github.io/FreshRSS/en/admins/02_Prerequisites.html

For Debian / Ubuntu, see the list of packages we are installing in our official Docker image:

https://github.com/FreshRSS/FreshRSS/blob/ac3dd96f48d2e95b5fd143ab0ca5606c36283c55/Docker/Dockerfile#L11-L12

**Comment by rezad1393** [comment]
can this be added to installation check page?

**Comment by Alkarex** [comment]
> can this be added to installation check page?

We could (PR welcome), although 32-bit is getting less and less common. And it is also in our documentation and Dockerfiles.
